### ISSUE TITLE
Windows creation in AWS might fail due to WinRM issues

### ISSUE THREAD

**Issue by elaurijssens** [imagecloud-io/image-factory#1]
##### SUMMARY

The Windows VMs in AWS regularly show WinRM failures. According to [this issue on GitHub](https://github.com/ansible/ansible/issues/23320) the Ansible developers are aware of it. We did discover that really strong passwords don't always work because they might contain characters that should be escaped in one shell but aren't recognized as such in the other. 
Another approach that seems to work is to sync the time right after deployment before doing anything 
with WinRM.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /Users/elaurijssens/imagecloud-io/image-factory/ansible.cfg
  configured module search path = [u'/Users/elaurijssens/imagecloud-io/image-factory/library', u'/Users/elaurijssens/.ansible/library', u'/usr/share/ansible/library']
  ansible python module location = /Users/elaurijssens/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /Users/elaurijssens/Library/Python/2.7/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### IMAGE

```
base_templates:
  aws_ec2:
    windows2016:
      description: "Windows 2016 Datacenter"
      instance_type: "t2.large"
      base_ami:
        name: "Windows_Server-2016-English-Full-Base*"
        owner: "amazon"
      guest_os: "windows"
      vm_name: "win2016"
      admin_user: "Administrator"
      user_data: "include/aws_ec2/windows2016.j2"
      baseline_accept:
        - "cis-network-access-2.2.2"
      encrypt: yes
      kms_key: "12345678-0123-4567-89ab-cdefdeadbeef" 
```

##### CLOUD

```
cloud_env:
  aws_demo:
    description: "AWS demo deployment"
    type: aws_ec2
    access_key: ABCDEFGHIJKLMNOPQRST
    keypair: "image-factory-key"
    sec_group: "image-factory-group"
    region: "eu-central-1"
    zone: "eu-central-1b"
    launch_ids:
      - "000000000000"
    vpc_id: "vpc-00000000"
    default_sec_rules:
      -
        proto: tcp
        ports:
          - 22
          - 3389
          - 5986
        cidr_ip: "0.0.0.0/0"
        cidr_ipv6: "::/0"
        rule_desc: "OS Management"
    wsus:
      wsus_client_enable: no
      wsus_client_server: http://wsushost.local
      wsus_client_detection_frequency: 1
      wsus_client_reboot_warning_timeout: 15
      wsus_client_reboot_launch_timeout: 5
      wsus_client_schedule_install_day: Everyday
      wsus_client_target_group: baseline

```

##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS

Windows run works immediately
##### ACTUAL RESULTS

Windows run fails with WinRM SSL errors or Access Denied errors

```

```
